### ISSUE TITLE
Cari Referensi

### ISSUE THREAD

**Issue by andiksugianto** [andiksugianto/opentrip#1]
Cari referensi web aplikasi terkait dengan aplikasi yang akan kita buat.

**Comment by andiksugianto** [comment]
gimana nih ?

**Comment by AzharKrisna** [comment]
woookeh kapten ane udah dapet referensinya
- http://pulauseribu-resorts.com
- http://www.traveloista.com
- http://www.nusatrip.com (Untuk Booking Hotelnya)
  Tolong di cek Capt!!!!

**Comment by andiksugianto** [comment]
cakep bro, http://www.traveloista.com/ada fitur semacam social media
http://pulauseribu-resorts.com/ hanya bisa reservasi, gak ada fitur open trip dan susun itenerary sendiri

Mungkin bisa padukan di aplikasi yang akan kita buat nanti.
thx bro

**Comment by AzharKrisna** [comment]
Yoooosh sama2 semangat semuaaaa hahahaha
